### ISSUE TITLE
"Unexpected BatchStatement" ERROR for every batch statement

### ISSUE THREAD

**Issue by stankelberg** [Ericsson/ecaudit#164] opened 2020-04-07 07:54 UTC
Cassandra 3.11.6, plugin c3.11_2.5.0

For every batch statement we get the following error in the cassandra logs:

**AuditEntryBuilderFactory.java:231 - Unexpected BatchStatement when mapping singe query for audit**

**Comment by millerjp** [comment] 2020-04-07 09:02
Is there a fix for this?

**Comment by emolsson** [comment] 2020-04-07 09:51
I'll look into it, I think the offending line which logs might be [this](https://github.com/Ericsson/ecaudit/blob/master/ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/entry/factory/AuditEntryBuilderFactory.java#L231) one.

Do you know how the batches are issued towards the cluster? E.g. is the batch itself prepared, a plain query from cqlsh or a batch request containing prepared statements?

**Comment by emolsson** [comment] 2020-04-07 12:28
It seems this can happen if the full batch request is prepared (current tests is using batch statements containing prepared statements).

I'll try to get a PR up today.

**Comment by stankelberg** [comment] 2020-04-07 13:35
Thanks!
We are still trying to identify the nature off batch statement from the app team.

Atm, I can say that when I run a simple BATCH with two INSERTS via cqlsh, i still get the same error in the system.log, the data is still written though.

In the app team case, they say only the 1st record of the batch gets written to Cassandra and they see the Unexpected BatchStatement  error returned from the driver. 

Btw, even when I added the user who runs the batch statement into the whitelist, I still get the same error in system.log

**Comment by emolsson** [comment] 2020-04-07 14:20
> Atm, I can say that when I run a simple BATCH with two INSERTS via cqlsh, i still get the same error in the system.log, the data is still written though.

I believe that is caused by one of the fail-safes, in debug level logging something like the following is likely written:
`Failed to parse or prepare statement - assuming default permissions and resources`

Which still logs entries and allows the request to proceed. The error log should be removed by the PR as well, but I'll add some additional test cases specifically for non-prepared batch statements.

> In the app team case, they say only the 1st record of the batch gets written to Cassandra and they see the Unexpected BatchStatement error returned from the driver.

Hmm.. I can't really imagine how this would happen right now. The whole batch should be treated as a single audit record. When the mentioned failure happens it should stop execution before any sub-request of the batch is performed at all.

Do you think it would be possible to show a simple example of how this batch request is built from client side?

> Btw, even when I added the user who runs the batch statement into the whitelist, I still get the same error in system.log

Unfortunately the error logging/throwing is part of building an audit entry. After the audit entry has been built it is matched against the whitelist - so the failure is slightly before the whitelisting can take place.

**Comment by stankelberg** [comment] 2020-04-07 14:32
> Do you think it would be possible to show a simple example of how this batch request is built from client side?

I'll try to get more details, so far don't take it as granted. Having only 1st insert from a batch is against the whole concept of batches, I would suspect they all failed. 

What we know for sure is the ERROR was returned back to the driver and the data was missing in Cassandra.

**Closed** 2020-04-08 13:46 UTC

**Comment by emolsson** [comment] 2020-04-08 13:48
It seems I accidentally closed the issue while merging the PR. We'll merge this forward to master and get this released. If you still encounter the issue in the new version, feel free to re-open the ticket!

**Comment by stankelberg** [comment] 2020-04-09 09:03
Thanks a lot for that!
Do you know when it's going to be released?  I assume it's going to be in 2.6.0? 

Thanks again!

**Comment by eperott** [comment] 2020-04-09 12:58
Right, this was just released in version 2.6.0.

It may take a few moments before artifacts are distributed to maven central.
